---
apiVersion: v1
kind: Service
metadata:
  name: harbor-scanner-trivy
spec:
  selector:
    app: harbor-scanner-trivy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-scanner-trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-scanner-trivy
  template:
    metadata:
      labels:
        app: harbor-scanner-trivy
    spec:
      initContainers:
        - name: init
          image: aquasec/harbor-scanner-trivy:dev
          imagePullPolicy: IfNotPresent
          command:
            - "trivy"
            - "--debug"
            - "--cache-dir=/root/.cache"
            - "--refresh"
          volumeMounts:
            - mountPath: /root/.cache
              name: trivy-cache
      containers:
        - name: main
          image: docker.io/aquasec/harbor-scanner-trivy:0.1.0-alpha.1
          imagePullPolicy: IfNotPresent
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: "info"
            - name: "SCANNER_API_SERVER_ADDR"
              value: ":8443"
            - name: "SCANNER_API_SERVER_TLS_CERTIFICATE"
              value: "/certs/tls.crt"
            - name: "SCANNER_API_SERVER_TLS_KEY"
              value: "/certs/tls.key"
            - name: "SCANNER_TRIVY_CACHE_DIR"
              value: "/root/.cache"
            - name: "SCANNER_STORE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
            - name: "SCANNER_STORE_REDIS_SCAN_JOB_TTL"
              value: "1h"
            - name: "SCANNER_JOB_QUEUE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
          ports:
            - name: api-server-port
              containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /probe/healthy
              port: api-server-port
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /probe/ready
              port: api-server-port
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          # TODO Use PersistentVolumeClaim to scale up scanner deployment
          volumeMounts:
            - mountPath: /root/.cache
              name: trivy-cache
            - mountPath: /data/scanner
              name: scanner-data
            - mountPath: /certs
              name: certs
              readOnly: true
      volumes:
        - name: trivy-cache
          hostPath:
            path: /data/trivy
        - name: scanner-data
          hostPath:
            path: /data/scanner/trivy
        - name: certs
          secret:
            secretName: harbor-scanner-trivy-tls
