---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-scanner-trivy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-scanner-trivy
  template:
    metadata:
      labels:
        app: harbor-scanner-trivy
    spec:
      initContainers:
        - name: init
          image: aquasec/harbor-scanner-trivy:poc
          imagePullPolicy: IfNotPresent
          command:
            - "trivy"
            - "--debug"
            - "--cache-dir=/root/.cache"
            - "--refresh"
          volumeMounts:
            - mountPath: /root/.cache
              name: trivy-cache
      containers:
        - name: main
          image: aquasec/harbor-scanner-trivy:poc
          imagePullPolicy: IfNotPresent
          env:
            - name: "SCANNER_API_ADDR"
              value: ":8080"
            - name: "SCANNER_TRIVY_CACHE_DIR"
              value: "/root/.cache"
            - name: "SCANNER_STORE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
            - name: "SCANNER_JOB_QUEUE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
          ports:
            - containerPort: 8080
          # TODO Use PersistentVolumeClaim to scale up scanner deployment
          volumeMounts:
            - mountPath: /root/.cache
              name: trivy-cache
            - mountPath: /data/scanner
              name: scanner-data
      volumes:
        - name: trivy-cache
          hostPath:
            path: /data/trivy
        - name: scanner-data
          hostPath:
            path: /data/scanner/trivy
---
apiVersion: v1
kind: Service
metadata:
  name: harbor-scanner-trivy
spec:
  selector:
    app: harbor-scanner-trivy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
