---
apiVersion: v1
kind: Service
metadata:
  name: harbor-scanner-trivy
spec:
  selector:
    app: harbor-scanner-trivy
  type: LoadBalancer
  ports:
    - name: api-server
      protocol: TCP
      port: 8443
      targetPort: 8443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-scanner-trivy
spec:
  serviceName: harbor-scanner-trivy
  selector:
    matchLabels:
      app: harbor-scanner-trivy
  replicas: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
  template:
    metadata:
      labels:
        app: harbor-scanner-trivy
    spec:
      initContainers:
        - name: init
          image: aquasec/harbor-scanner-trivy:0.1.0-beta.1
          imagePullPolicy: IfNotPresent
          command:
            - "trivy"
            - "--debug"
            - "--no-progress"
            - "--cache-dir=/root/.cache/trivy"
            - "--refresh"
          volumeMounts:
            - mountPath: /root/.cache
              name: data
          resources:
            requests:
              cpu: 200m
              memory: 1500Mi
            limits:
              cpu: 1
              memory: 2Gi
          securityContext:
            readOnlyRootFilesystem: false
      containers:
        - name: main
          image: aquasec/harbor-scanner-trivy:0.1.0-beta.1
          imagePullPolicy: IfNotPresent
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: "info"
            - name: "SCANNER_API_SERVER_ADDR"
              value: ":8443"
            - name: "SCANNER_API_SERVER_TLS_CERTIFICATE"
              value: "/certs/tls.crt"
            - name: "SCANNER_API_SERVER_TLS_KEY"
              value: "/certs/tls.key"
            - name: "SCANNER_TRIVY_CACHE_DIR"
              value: "/root/.cache/trivy"
            - name: "SCANNER_TRIVY_REPORTS_DIR"
              value: "/root/.cache/reports"
            - name: "SCANNER_STORE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
            - name: "SCANNER_STORE_REDIS_SCAN_JOB_TTL"
              value: "1h"
            - name: "SCANNER_JOB_QUEUE_REDIS_URL"
              value: "redis://harbor-harbor-redis:6379"
          ports:
            - name: api-server
              containerPort: 8443
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /probe/healthy
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /probe/ready
              port: api-server
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - mountPath: /root/.cache
              name: data
            - mountPath: /certs
              name: certs
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: certs
          secret:
            secretName: harbor-scanner-trivy-tls
