apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-scanner-trivy.fullname" . }}
  labels:
{{ include "harbor-scanner-trivy.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "harbor-scanner-trivy.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - name: api-server
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}