name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup make
        run: make setup
      - name: Run linter
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Run integration tests
        run: make test-integration
      - name: Run component tests
        run: make test-component
      - name: Login to docker.io registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.148.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Log out from docker.io registry
        if: ${{ always() }}
        run: |
          docker logout docker.io
