name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unshallow # This step is required for the changelog to work correctly
        run: git fetch --prune --unshallow
      - name: Setup make
        run: make setup
      - name: Run linter
        run: make lint
      - name: Run unit tests
        run: make test
      - name: Run integration tests
        run: make test-integration
      - name: Login to DockerHub Registry
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USER }} --password-stdin
      - name: Release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
